import Header from '@/components/header/Header'
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'A2SV',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="font-Montserrat bg-background">
        <Header/>
        {children}
        </body>
    </html>
  )
}
