import './globals.css'
import type { Metadata } from 'next';
import ReduxProvider from '@/components/blog/ReduxProvider';

export const metadata: Metadata = {
  title: 'A2SV',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='font-Montserrat'>
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
      
    </html>
  )
}
