import "./globals.css";
import type { Metadata } from "next";
import ReduxProvider from "@/components/blog/ReduxProvider";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import { ScrollToTop } from "@/components/home/ScrollToTop";

export const metadata: Metadata = {
  title: "A2SV",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-Montserrat">
        <ReduxProvider>
          <Header />
          {children}
          <ToastContainer
            position="top-right"
            autoClose={2000}
            hideProgressBar
            newestOnTop={false}
            closeOnClick
            rtl={false}
            draggable
            pauseOnHover
          />
        </ReduxProvider>
        <ScrollToTop />
        <Footer />
      </body>
    </html>
  );
}
