// Mocks generated by Mockito 5.4.2 from annotations
// in blog_app/test/features/profile/data/repository/profile_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:blog_app/core/network/network_info.dart' as _i8;
import 'package:blog_app/features/profile/data/data_sources/profile_local_data_source.dart'
    as _i6;
import 'package:blog_app/features/profile/data/data_sources/profile_remote_data_source.dart'
    as _i3;
import 'package:blog_app/features/profile/domain/entity/article.dart' as _i7;
import 'package:blog_app/features/profile/domain/entity/profile.dart' as _i2;
import 'package:image_picker/image_picker.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProfile_0 extends _i1.SmartFake implements _i2.Profile {
  _FakeProfile_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProfileRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRemoteDataSource extends _i1.Mock
    implements _i3.ProfileRemoteDataSource {
  @override
  _i4.Future<_i2.Profile> getProfile() => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
        ),
        returnValue: _i4.Future<_i2.Profile>.value(_FakeProfile_0(
          this,
          Invocation.method(
            #getProfile,
            [],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Profile>.value(_FakeProfile_0(
          this,
          Invocation.method(
            #getProfile,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Profile>);
  @override
  _i4.Future<_i2.Profile> updateProfilePicture(_i5.XFile? photoFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfilePicture,
          [photoFile],
        ),
        returnValue: _i4.Future<_i2.Profile>.value(_FakeProfile_0(
          this,
          Invocation.method(
            #updateProfilePicture,
            [photoFile],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Profile>.value(_FakeProfile_0(
          this,
          Invocation.method(
            #updateProfilePicture,
            [photoFile],
          ),
        )),
      ) as _i4.Future<_i2.Profile>);
}

/// A class which mocks [ProfileLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileLocalDataSource extends _i1.Mock
    implements _i6.ProfileLocalDataSource {
  @override
  _i4.Future<List<_i7.Article>> getBookmarkArticles() => (super.noSuchMethod(
        Invocation.method(
          #getBookmarkArticles,
          [],
        ),
        returnValue: _i4.Future<List<_i7.Article>>.value(<_i7.Article>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i7.Article>>.value(<_i7.Article>[]),
      ) as _i4.Future<List<_i7.Article>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i8.NetworkInfo {
  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
