// Mocks generated by Mockito 5.4.2 from annotations
// in blog_app/test/features/profile/domain/use_case/update_profile_picture_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:blog_app/core/error/failure.dart' as _i5;
import 'package:blog_app/features/profile/domain/entity/profile.dart' as _i6;
import 'package:blog_app/features/profile/domain/repositories/profile_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:image_picker/image_picker.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i3.ProfileRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Profile>> getProfile() =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Profile>>.value(
            _FakeEither_0<_i5.Failure, _i6.Profile>(
          this,
          Invocation.method(
            #getProfile,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.Profile>>.value(
                _FakeEither_0<_i5.Failure, _i6.Profile>(
          this,
          Invocation.method(
            #getProfile,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Profile>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Profile>> updateProfilePicture(
          _i7.XFile? image) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfilePicture,
          [image],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Profile>>.value(
            _FakeEither_0<_i5.Failure, _i6.Profile>(
          this,
          Invocation.method(
            #updateProfilePicture,
            [image],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.Profile>>.value(
                _FakeEither_0<_i5.Failure, _i6.Profile>(
          this,
          Invocation.method(
            #updateProfilePicture,
            [image],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Profile>>);
}
