import "./globals.css";
import type { Metadata } from "next";
import { Inter,Lato, Nunito, Poppins  } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const lato = Lato({
  subsets: ['latin'], variable: '--font-lato', weight: ['100','300','400','700','900']
})

const nunito = Nunito({
  subsets: ['latin'], variable: '--font-nunito'
})

const poppins = Poppins({
  subsets: ['latin'], variable: '--font-poppins', weight: ['100','300','400','700','900']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={`${poppins.className} ${nunito.className} ${lato.className}`}>
      <body>{children}</body>
    </html>
  );
}
