"use client";

import { Provider } from "react-redux";
import { NavBar } from "@/components/NavBar";
import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";

const inter = Poppins({
  weight: "400",
  subsets: ["latin"],
});
import StateProvider from "@/components/provider/StateProvider";
import Footer from "@/components/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StateProvider>
      <html lang="en">
        <body className={`flex flex-col ${inter.className}`}>
          <header>
            <NavBar />
          </header>
          <main>{children}</main>
          <Footer />
        </body>
      </html>
    </StateProvider>
  );
}
